### ISSUE TITLE
Convert C# managed to native C++

### ISSUE THREAD

**Issue by gnations56** [popa6200/Network-everywhere-client-r2#1]
Currently the support library in DLL's is using the C++ to managed C# bridge in windows. However, this will NOT work on Linux so we need to write native code at least for Linux and activate it using preprocessor directives primarily:
 `__linux__` for Linux
`__WIN64__` for 64-bit windows

We need to look for a cross platform socket library like SFML for Linux and on Windows we should use native API's for best performance

**Comment by popa6200** [comment]
SFML is platform-independent, I have attempted to use the native networking library provided in `windows.h` and it is deemed as a false positive for some AV (*cough* AVG *cough*)
