### ISSUE TITLE
Client Communications System

### ISSUE THREAD

**Issue by gnations56** [popa6200/Network-everywhere-client-r2#2]
There should be a decision on whether or not to use raw packets or some sort of message queue with checksum and noSQL db.

**Comment by popa6200** [comment]
I think it might be better to use the latter, there are too many variables to stream raw data, without worrying about discrepancy between the sent and received messages.

**Comment by gnations56** [comment]
ok i will try mongodb and rabbitmq for that.
Can you call me on discord at 6:30 today?

**Comment by popa6200** [comment]
Ok, I'll try.

**Comment by gnations56** [comment]
i will have docker containers up and ready for testing then
